// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7EaqmuOOpdnQ_5ms7gwadZifKkYgqB0s',
    appId: '1:709832797690:web:c293d83d4d38e03cae8843',
    messagingSenderId: '709832797690',
    projectId: 'project06-49a5b',
    authDomain: 'project06-49a5b.firebaseapp.com',
    storageBucket: 'project06-49a5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfOjGC5762onjcI-oGd3NLS3vZwZ44sA',
    appId: '1:709832797690:android:ca705d8b8639e230ae8843',
    messagingSenderId: '709832797690',
    projectId: 'project06-49a5b',
    storageBucket: 'project06-49a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJrGLHc7DL7AxlKp4X0oUfuLnW2EIzIE',
    appId: '1:709832797690:ios:142e8327f5cec2a3ae8843',
    messagingSenderId: '709832797690',
    projectId: 'project06-49a5b',
    storageBucket: 'project06-49a5b.appspot.com',
    iosBundleId: 'com.example.flutterAppResto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJrGLHc7DL7AxlKp4X0oUfuLnW2EIzIE',
    appId: '1:709832797690:ios:07c9246b03e7148fae8843',
    messagingSenderId: '709832797690',
    projectId: 'project06-49a5b',
    storageBucket: 'project06-49a5b.appspot.com',
    iosBundleId: 'com.example.flutterAppResto.RunnerTests',
  );
}
